### ISSUE TITLE
Documentation navigation could be clearer

### ISSUE THREAD

**Issue by nkurz** [elixir-lang/elixir-lang.github.com#822] opened 2016-08-04 19:45 UTC
Your already excellent documentation would benefit from better navigation clues.  This thread shows a potential new user who never discovered the depth of the manual: https://news.ycombinator.com/item?id=12224631

Some approaches you might consider if you conclude this is a real issue:

* Use a 1.A numbering scheme for Chapter and Section.
* Add Chapter numbers to URL's and Section letters to anchors.
* Highlight the current position in right column index.
* Add a "single page" link  (HTML, PDF, or both).
* Make the "Next" link more prominent and clarify it's destination.

One can easily argue that none of these are necessary, but considering the extreme effort that you've already put into creating great documentation, it's sad that someone would not be able to make use of it.

**Comment by josevalim** [comment] 2016-08-04 20:13
Thank you. I think we could at least change the numeration scheme. I don't think we should add the chapter numbers to URLs though because that means changing URLs when a new chapter is added in the middle.

**Comment by josevalim** [comment] 2016-08-04 20:14
@nkurz btw the user replied he/she didn't see the Getting Started after installation, so I am not sure those would have effectively helped him/her. So maybe we should add a link to the getting started guide in the installation section.

**Comment by kenips** [comment] 2016-08-05 18:27
@josevalim what do you think of renaming "Getting Started" to "Guide"? and "Learning" to "Resources"? Seems like people clicked learning expecting to find guide instead.

**Comment by josevalim** [comment] 2016-08-05 18:37
@kenips the first paragraph of "Learning" says: "Our website provides a Getting Started guide to learn more about Elixir’s foundation and explore how to build projects with Mix and OTP.".

So taking any decision here is really hard because the person did not read even the first paragraph of the learning section (or they read and didn't understand it). How can we improve anything based on that? :(

**Comment by kenips** [comment] 2016-08-06 00:08
I'm totally with you here, but I can also understand that people don't read these days. It's still our job to improve the user experience though :). So really we are shortening "Getting Started Guide" to "Guide" and "Learning Resources" to "Resources" which is more appropriate IMO. I think it's also beneficial for those who read carefully not to find that that the "Getting Started" section is the guide that they wanted from the "Learning" section.

**Comment by josevalim** [comment] 2016-08-06 00:40
The issue is that "Resources" doesn't tell me it is for learning, "Guide" doesn't tell me what it is guiding for. I think the proposed words make it much less clear. :(

**Comment by kenips** [comment] 2016-08-09 18:25
@josevalim from the user experience perspectively I think whatever has *least surprise* is the best. You can see that:

Rails -
<img width="814" alt="screen shot 2016-08-09 at 2 13 59 pm" src="https://cloud.githubusercontent.com/assets/794915/17528002/8d8c0eec-5e3b-11e6-9408-78823fe4c72f.png">

React -
<img width="281" alt="screen shot 2016-08-09 at 2 14 23 pm" src="https://cloud.githubusercontent.com/assets/794915/17528012/9b7bb368-5e3b-11e6-8b7f-371809f822f9.png">

Clojure -
<img width="402" alt="screen shot 2016-08-09 at 2 14 50 pm" src="https://cloud.githubusercontent.com/assets/794915/17528029/acb80d8e-5e3b-11e6-949b-615032c2c750.png">

Phoenix -
<img width="797" alt="screen shot 2016-08-09 at 2 15 15 pm" src="https://cloud.githubusercontent.com/assets/794915/17528037/bc813ee8-5e3b-11e6-9527-55fc6dc6fc81.png">

All use "Guides" as a more in-depth tutorial of the language. Whereas "Getting started" is for installation and hello world example. I'd say that the industry has settled on "Guides". Thoughts?

**Comment by josevalim** [comment] 2016-08-10 07:52
We have renamed "Getting started" to "Guides".

**Comment by kenips** [comment] 2016-08-10 14:58
❤️❤️❤️ you're my hero 🙇  @josevalim

**Comment by josevalim** [comment] 2016-10-29 09:16
I am closing this as I believe we have tackled the main issue? We also have another open issue to provide an EPUB version of the guides. :)

**Closed by josevalim** 2016-10-29 09:16 UTC
